name: MUZ
main: dev.mumu.doudizhu.DoudizhuPlugin
version: ${version}
api-version: "${apiVersion}"
folia-supported: true
author: linmumua
description: MUZ card table plugin for Paper and Purpur.
softdepend:
  - CraftEngine
  - PlaceholderAPI
  - Vault
  - CMI
  - CMILib
  - EzEconomy
  - XConomy
permissions:
  muz.admin:
    default: op

